live_config_reload = true

import = [
    "~/.config/alacritty/gnome-terminal.toml"
]

[env]
TERM = "alacritty"

[cursor.style]
shape = "Block"

[font]
size = 20

[font.normal]
family = "Fira Code"

[scrolling]
history = 100000

[window]
opacity = 0.9
