live_config_reload = true

[env]
TERM = "alacritty"

[font]
size = 15

[font.normal]
family = "Fira Code"
style = "Medium"

[scrolling]
history = 100000

[colors.primary]
background = "0x0a0a0a"

[window]
dynamic_title = true
dynamic_padding = true
opacity = 1.0

